---
- hosts: mysql_instance
  become: true
  vars:
    - webserver_port: 80

  vars_files:
    - vars/wordpress.yml
    - vars/wordpress_vault.yml

  tasks:
    - name: Validating if the NGINX is UP and OPENED the PORT
      tags: nginxvalidate1
      ansible.builtin.wait_for:
        port: "{{webserver_port}}"
        delay: 10
        timeout: 30
        state: started
        msg: "NGINX PORT is not Listening"
      register: nginxvalidate1
      ignore_errors: true

    - name: Make sure a service nginx is running
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
      ignore_errors: true

    - name: Make sure a service mysql is running
      ansible.builtin.systemd:
        name: mysql
        state: started
        enabled: true
      ignore_errors: true
      delegate_to: "{{ inventory_hostname }}"

    # - name: Check mysql is working properly
    #   ansible.builtin.shell: "mysqladmin -u {{ mysql_user }} -p status"
    #   delegate_to: "{{ inventory_hostname }}"
    #   ignore_errors: true

    - name: create a backup
      mysql_db:
        name: wordpress
        state: dump
        target: /var/www/html/wordpress.sql
        login_host: localhost
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
      run_once: true
