---
- hosts: ubuntus
  become: true

  vars_files:
    - vars/wordpress.yml
    - vars/wordpress_vault.yml

  roles:
    - {role: ansible-role-nginx, tags: [nginx]}
    - {role: ansible-role-php, tags: [php]}
    - {role: ansible-role-mysql, tags: [mysql]}
    - {role: wordpress, tags: [wordpress]}
...
