---
# tasks file for wordpress
# WordPress Configuration
- name: Setup wordpress
  include_tasks: wp_setup.yml
  when: setup | default("false") | bool

- name: Config wordpress
  include_tasks: wp_config.yml
  when: owners | default("true") | bool

- name: Set ownership
  include_tasks: wp_owners.yml
    
- name: Set permissions
  include_tasks: wp_permissions.yml
    
- name: Inform me about the final
  include_tasks: optional.yml
  when: inform | default('false') | bool  
...

