---
- name: Update apt cache and install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Apply Nginx template for index.html
  ansible.builtin.template:
    # src: index.html.j2
    src: "{{ index_file }}.j2"
    dest: "{{ document_root }}/{{ index_file }}"
    mode: '0644'
  notify: Restart Nginx

- name: Allow all access to tcp port 80
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
